name:                hledger-api
version:             0.1.0.0
github:              "wolfsblu/hledger-api"
license:             AGPL-3.0 
author:              "Lukas Wolfsberger"
maintainer:          "1245519+wolfsblu@users.noreply.github.com"
copyright:           "2025 Lukas Wolfsberger"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/wolfsblu/hledger-api#readme>

dependencies:
- base >= 4.7 && < 5
- hledger-lib >= 1.43
- servant >= 0.20
- servant-server >= 0.20
- servant-openapi3 >= 2.0
- openapi3 >= 3.2
- insert-ordered-containers
- aeson >= 2.0
- warp >= 3.3
- wai >= 3.2
- wai-cors >= 0.2
- text
- time
- bytestring
- lens
- mtl
- containers
- optparse-applicative >= 0.18
- scientific
- directory
- filepath
- transformers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  hledger-api-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hledger-api

tests:
  hledger-api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hledger-api
